package kotlintutorial

//class with default primary constructor accepting two string args. Refer Kotlin3
class Person (fName: String, lName: String){
    init {
        println("init 1")
    }
    //secondary constructor. In general we dont need secondary constructors coz we can add default values to the strings
    // in primary constructir itself.
    constructor():this("defaultfirst","default last"){
        println("secondary")
    }



    //init blocks are always run before the secondary constructor
    init {
        println("init2")
    }
    var firstName: String = fName
    var lastName: String = lName

    var mobile: String? = null
        set(value) {
            field = value//field here is automatically the field just above this line which is mobile. see I have given a tab.
            println("overriding default getter generated by kotlin $value")
        }
        get() {
            println("overriding default getter generated by kotlin $field")
            return field
        }
    //cimilar to static
    init {
        firstName = "judi"
    }

    fun getFullName(): String {
        //since mobile is nullable lets check if mobile is null and print only if not null with elvis operator
        var mobileNotNull = mobile?:"no mobile"//if mobile is null then its set to no mobile
        return firstName + lastName + mobileNotNull;
    }

    //visibility is by default public we can also make methods.

}